### PR TITLE
[BL-5917] Fix bug where WebView scale was not being set when the devi…

### PR DESCRIPTION
**Pull request by rjconrad**
Fix bug where WebView scale was not being set when the device orientation changed to match book orientation.

https://issues.bloomlibrary.org/youtrack/issue/BL-5917

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/123)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 970 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomreader/123#-LAYRcaC604G2oyP_F9c:-LAYRcaC604G2oyP_F9d:b-q0yo7i) ([raw file](https://github.com/bloombooks/bloomreader/blob/d6b71f9d4e40d9488251175a8db08dcb4c48d2b7/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L970)):*
> ```Java
> 
>                     // The viewport ratio can change with orientation changes when the Back/Home/Recent menu moves to a different side
>                     // Unfortunately we can't rescale a Webview once it's been scaled, so if we want to fix this, we'll have to make a new Webview
> ```

How likely is this scenario? How hard is it to make a new Webview?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomreader/123)*

**Comment by andrew-polk** [comment]
Should we consider this fix for 1.1?

**Comment by rjconrad** [comment]
The problem might not exist on 1.1. I think this is a side-effect of the work we did to support MotionBooks.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 970 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomreader/123#-LAYRcaC604G2oyP_F9c:-LAYXwvR3yTPT65WnGp-:b-dyxaf9) ([raw file](https://github.com/bloombooks/bloomreader/blob/d6b71f9d4e40d9488251175a8db08dcb4c48d2b7/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L970)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How likely is this scenario? How hard is it to make a new Webview?
</blockquote></details>

It can only happen on books that switch between Portrait and Landscape when the user rotates the phone.  Right now I think that's not the common case, so I restricted this PR to solving the easier and more urgent problem.

I'll make a separate issue for tracking.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomreader/123#-:-LAYYeXtCLMEmXERIQjb:b-9x0loi)*

**Comment by rjconrad** [comment]
Just confirmed, the bug doesn't exist on 1.1.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomreader/123#-:-LAYb7bf8ybr70CphB1r:b-qlsbwr)*

**Comment by andrew-polk** [comment]
> Just confirmed, the bug doesn't exist on 1.1.

Great. Thanks.
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 970 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomreader/123#-LAYRcaC604G2oyP_F9c:-LAYeMGM0BlDVb6RY777:b4c9lyr) ([raw file](https://github.com/bloombooks/bloomreader/blob/d6b71f9d4e40d9488251175a8db08dcb4c48d2b7/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L970)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

It can only happen on books that switch between Portrait and Landscape when the user rotates the phone.  Right now I think that's not the common case, so I restricted this PR to solving the easier and more urgent problem.

I'll make a separate issue for tracking.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomreader/123#-:-LAYeGdg5k3u-zpOPHOw:bw40e9v)*

**Pull request merged**
