### PR TITLE
[BL-5237] Properly display landscape books.

### PR DESCRIPTION
**Pull request by rjconrad**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/75)

### CODE REVIEW

**Comment by rjconrad** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 390 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_Xq-M5B9GMradDacQ:-Ky_Xq-M5B9GMradDacR:b-geqrsx) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L390)):*
> ```Java
>         //but for now, they are the width and height of the Device16x9Portrait layout
>         int bookPageWidth = (bookOrientation == ScaledWebView.BOOK_PORTRAIT) ? 378 : 674;
>         int bookPageHeight = (bookOrientation == ScaledWebView.BOOK_PORTRAIT) ? 674 : 378;
> ```

I'm not sure where the 378 and 674 come from. Seems like they must be based on the 100mm x 178mm in the css, but I haven't figured out the conversion. 

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-Ky_YNdqU32YNrs1wHKN:b-6s0ujd) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
> ```Java
>                 }
>                 // Styles to force 0 border and to vertically center landscape books in a portrait browser
>                 String moreStyles = "<style>html{ height: 100%; }  body{ min-height:100%; display:flex; align-items:center; } div.bloom-page { border:0 !important; }</style>\n";
> ```

Is there a better place to put these styles?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-KyqIcnufwKz_xIbGK2P:b-smru0q) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

Is there a better place to put these styles?
</blockquote></details>

Yes... 
Well, one option is to add another css file similar to assets.css.
Another option is to push it in from BloomDesktop. I know we had similar discussions in the past and decided to push styles in from BD, but now I can't remember the exact discussion or if it is the same scenario. @Hatton? @JohnThomson?

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 513 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-KyqHTZJ5vyeNqwjErDP:-KyqHTZJ5vyeNqwjErDQ:bcb8ev6) ([raw file](https://github.com/bloombooks/bloomreader/blob/ff0980a7674bad5972ba3192b5c0f37e10c72821/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L513)):*
> page = modifyPage(page, "Device16x9Portrait", "border:0 !important");

I'm pretty sure this is still necessary. On the Bloom side, I don't think we force one of those two layouts; thus Bloom Reader must.
I think you can just assume every layout will have "Portrait" or "Landscape" in it and force the device layout appropriately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-KyqfLd0PqhVr8V9pAQu:b-gw7jam) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes... 
Well, one option is to add another css file similar to assets.css.
Another option is to push it in from BloomDesktop. I know we had similar discussions in the past and decided to push styles in from BD, but now I can't remember the exact discussion or if it is the same scenario. @Hatton? @JohnThomson?
</blockquote></details>

I'm thinking we should have an alternative styelsheet in BD, and just us that if the book has "landscape" in the name it its layout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-KyqfvoGedkZaB5KfYjG:bg5cz5i) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm thinking we should have an alternative styelsheet in BD, and just us that if the book has "landscape" in the name it its layout.
</blockquote></details>

Or rather, whatever... to invoke the same rules as we have in basepage.css? Sorry I don't know how the current stylesheet system is working in BR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75)*

**Comment by rjconrad** [comment]
I started out by simply making every page either Device16x9Portrait or Device16x9Landscape as appropriate, and that worked pretty well. However, on at least one of my books, some of the words were being cut off because the aspect ratio had changed. So now I have it scaling based of the original page dimensions (A4, Letter...), but also changing the layout class to Device16x9X because there's other styles related to that.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-KyzQMcnnalIE6ulfLnk:b-gwohwb) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Or rather, whatever... to invoke the same rules as we have in basepage.css? Sorry I don't know how the current stylesheet system is working in BR.
</blockquote></details>

The styles have moved to moreStyles() and some of them are dynamic now.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 513 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-KyqHTZJ5vyeNqwjErDP:-KyzQYBOLqZo_tLMJRaH:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/ff0980a7674bad5972ba3192b5c0f37e10c72821/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L513)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> page = modifyPage(page, "Device16x9Portrait", "border:0 !important");

I'm pretty sure this is still necessary. On the Bloom side, I don't think we force one of those two layouts; thus Bloom Reader must.
I think you can just assume every layout will have "Portrait" or "Landscape" in it and force the device layout appropriately.


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-:-KyzPP4dD2zO0YFw0XNZ:b-m526eo)*

**Comment by hatton** [comment]
Rick, while it might make sense at some point to abandon WYSIWYG to optimize for screens or whatever. But for now, let's stick to just applying the stylesheets so that people can see exactly what they are going to get, by just applying the stylesheet.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-:-Kyzt7DvvhMRksLBignL:b-cli2ae)*

**Comment by rjconrad** [comment]
We're closer to WYSIWYG with this PR than we were before. Now instead of making every page 16x9, the aspect ratio is the same as how the page was designed and all the page's contents scale with the page. I did preserve the previous behavior of applying the Device16x9 class to bloom-page divs which, for instance, moves the page number to the middle of the bottom of the page instead of having it on the side.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-:-KyztweLV0YnNQAT-xuG:b-4y453e)*

**Comment by hatton** [comment]
> words were being cut off because the aspect ratio had changed

Sorry, I not getting it. Both the Bloom Desktop and Bloom Reader are displaying pages using a browser and CSS stylesheet named Device16x9Landscape. But if I understand you correctly,  then on the phone, that stylesheet is not reproducing the same thing as on the desktop. In that case, we need to fix the stylesheet somehow. Right? Feel free to jump on Flowdock Bloom channel to discuss further.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-:-KyzyJeGfeYlfANgxBE8:b-7j45be)*

**Comment by JohnThomson** [comment]
I'm puzzled too. Rick, could you be working with some old books? The current Bloom should be forcing every book you transfer to be device16x9. I would think it was part of this task to relax that and make it force every book transferred to be either device16x9 or device9x16 based on whether the original layout is portrait or landscape. If the user wants true wysiwyg he should create (or check) the book in one of those layouts. The reader should not have to be smart about applying a different layout...I think the code that was trying to do that was left over from before we made the desktop enforce the correct layout.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-:-Kz-59x8C9m911--wfM3:b-280ies)*

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 390 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_Xq-M5B9GMradDacQ:-Kz5pJMNcJnWGRSpRQwD:bcn0twu) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L390)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

I'm not sure where the 378 and 674 come from. Seems like they must be based on the 100mm x 178mm in the css, but I haven't figured out the conversion. 
</blockquote></details>

Yah. This commit trades a comment in the source for one that will be lost to Reviewable :-) Can you put the comment back in or add your own?

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-Kz5pmdWRNXDs_JQIay6:b-j6f2wv) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

The styles have moved to moreStyles() and some of them are dynamic now.
</blockquote></details>

I don't understand your reply, but I'll buy (with a bit of a squint) that it's ok to just use some CSS to do some positioning on the page. But I do see that your comment in the code says that it is for centering landscape books in a portrait browser... that surprises me; would have thought that you would tell the device to go into landscape mode so that swiping works as expected and (future) controls show up where expected? Or doe that all work out some other way already?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75)*

**Comment by rjconrad** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 390 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_Xq-M5B9GMradDacQ:-KyzQaxwdZ6PeUhtfr-h:b-sdltit) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L390)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yah. This commit trades a comment in the source for one that will be lost to Reviewable :-) Can you put the comment back in or add your own?
</blockquote></details>

That comment helped lead me down the path of calculating the actual dimensions for the page,which turned out not to be what you wanted. We always want the page dimensions to be those of Device16x9.

How about // 378x674 - the dimensions of the Device16x9 layout class in pixels

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-Kz8jes5HRrpZ06IG0ts:b94zlyk) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't understand your reply, but I'll buy (with a bit of a squint) that it's ok to just use some CSS to do some positioning on the page. But I do see that your comment in the code says that it is for centering landscape books in a portrait browser... that surprises me; would have thought that you would tell the device to go into landscape mode so that swiping works as expected and (future) controls show up where expected? Or doe that all work out some other way already?
</blockquote></details>

I made that comment on the last revision when it was true. The styles have moved back to where they were before. They could go anywhere, really, except maybe the 0 border which I think is supposed to be different between BD and BR. (I don't know much about that, it was already in BR in another place (the old modifyPage() method)).

We're letting the device orientation be based on the way the user is holding it. If the book is portrait and the device is landscape, it's letterboxed on the sides. If the book is landscape and the device is portrait it's letterboxed on top and bottom. This is the default android behavior, it's intuitive for the user, and it follows the pattern of other apps such as the photo gallery. Also if the device screen has some aspect ratio other than 16x9, the books will still look natural.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75)*

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 506 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/75#-Ky_YNdqU32YNrs1wHKM:-KzydPvAFibuXMX8lymc:b1tn9lz) ([raw file](https://github.com/bloombooks/bloomreader/blob/1a90adbde9a2da28825823bfca419b8a86c3277c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L506)):*
> We're letting the device orientation be based on the way the user is holding it. If the book is portrait and the device is landscape, it's letterboxed on the sides

Hmm, ok well that is not according to the design. Not clear when/why that happened.

What I'm wanting is that the orientation never changes, regardless of how you hold it. The orientation is determined by the book publisher.

Can you make that change? Thx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/75)*

**Comment by andrew-polk** [comment]
Superceded by #82

**Pull request closed without merging**
