### PR TITLE
 BL-5085 Verify External Media is mounted when we access our books directory

### PR DESCRIPTION
**Pull request by rjconrad**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/49)

### CODE REVIEW

**Comment by andrew-polk** [comment]
One minor thing. Otherwise, :lgtm:
Moving to Ready for UI Review

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/models/ExtStorageUnavailableException.java, line 11 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5FJgrQq7WRRhLCbI9:-Kw5FJgrQq7WRRhLCbIA:b-s3cf0k) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/ExtStorageUnavailableException.java#L11)):*
> "Unable to access file storage. Is the SD card missing?"

Should this be in strings.xml?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-:-Kw5FNFG6-sJ74KxiSml:b-7t1hxr)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 61 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5Vu_5evn7ZwBHlBZo:-Kw5Vu_5evn7ZwBHlBZp:bkqrcef) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L61)):*
> ```Java
>         SharedPreferences values = context.getSharedPreferences(BloomReaderApplication.SHARED_PREFERENCES_TAG, 0);
>         if(values.getBoolean(BloomReaderApplication.FIRST_RUN, true)){
>             SampleBookLoader.CopySampleBooksFromAssetsIntoBooksFolder(context, mLocalBooksDirectory);
> ```

If we were to put out an update that copied in a second book, or a different book, or just a changed "Moon & Cap", would this still run? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/49)*

**Comment by rjconrad** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 61 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5Vu_5evn7ZwBHlBZo:-Kw5YG7txSp6mlSNc4s3:b-6d38h3) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L61)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If we were to put out an update that copied in a second book, or a different book, or just a changed "Moon & Cap", would this still run? 
</blockquote></details>

No, it only runs the first time we run the app. 

The code that was there wouldn't have copied a new book either, but it was copying Moon and Cap every single time the main activity was created.

---

*[app/src/main/java/org/sil/bloom/reader/models/ExtStorageUnavailableException.java, line 11 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5FJgrQq7WRRhLCbI9:-Kw5XmQur_RFFJDmTWRi:bb77uci) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/ExtStorageUnavailableException.java#L11)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> "Unable to access file storage. Is the SD card missing?"

Should this be in strings.xml?
</blockquote></details>

Yep!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/49)*

**Comment by hatton** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 61 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5Vu_5evn7ZwBHlBZo:-Kw5bGvPlQKzdQYmy9cK:b3kwz9a) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L61)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

No, it only runs the first time we run the app. 

The code that was there wouldn't have copied a new book either, but it was copying Moon and Cap every single time the main activity was created.
</blockquote></details>

Sorry if I'm being dense... why would the old code not have copied any new books that we put in the "sample books" folder?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/49)*

**Comment by hatton** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 61 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5Vu_5evn7ZwBHlBZo:-Kw5eYoC02-UhisZ65_b:b-5msmo5) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L61)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>



This is what I was looking at. It only copies a file named "The Moon and the Cap.bloomd". So it would copy a new version of that book, but not any other books.
</blockquote></details>

Ok, thanks. I don't know why that is hard coded. But in any case, we could fix that or hard code more in order to distribute other books.

So we have to address that we would have to disable this current enhancement the next time we enhance M&C. Better if we can just put something smarter in place now, e.g. compare what's there and copy it only if it looks new or missing. It would be good to not keep replacing their M&C if they keep deleting it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/49)*

**Comment by rjconrad** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 61 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5Vu_5evn7ZwBHlBZo:-KwAFK2d8VB-lh54At2J:b55g0i9) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L61)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ok, thanks. I don't know why that is hard coded. But in any case, we could fix that or hard code more in order to distribute other books.

So we have to address that we would have to disable this current enhancement the next time we enhance M&C. Better if we can just put something smarter in place now, e.g. compare what's there and copy it only if it looks new or missing. It would be good to not keep replacing their M&C if they keep deleting it.
</blockquote></details>

This version runs the Sample Books copy any time we're running a new version for the first time.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/49)*

**Comment by hatton** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 61 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/49#-Kw5Vu_5evn7ZwBHlBZo:-KwAeX8dh25IUvZWSNoT:b-j6u9bs) ([raw file](https://github.com/bloombooks/bloomreader/blob/23fb2254ccee2c3f72f5b46696698ccb6b9c7a41/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L61)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

This version runs the Sample Books copy any time we're running a new version for the first time.  
</blockquote></details>

Perfect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/49)*

**Pull request merged**
