### PR TITLE
Success/Failure toasts for initial load of Device ID JSON.

### PR DESCRIPTION
**Pull request by rjconrad**
During application onCreate, if there is no stored Device Id in the SharedPrefs, we check for a json file. If we succeed in parsing the file, there's a success toast. If we find a file but fail to parse it, there's a failure toast. Once device id metadata is loaded, we never look at the json again. This means changing the metadata requires a reinstall.

For the people loading the json file, once the file is transferred, they need to make sure BR is closed. Then they should run it and watch for the success message.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/59)

### CODE REVIEW

**Comment by JohnThomson** [comment]
It would be pretty easy to make it check the json each time. But changing the device ID is something of a big deal...analytics will presumably report it as a different device, and confusingly, we would never get analytics saying Bloom was installed on that device. So you're probably right to make it quite hard to change. @hatton, what do you think?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, line 112 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/59#-KxNuWcpdy_XdonDQABC:-KxNuBKdlCS3LNM69Q4R:bosz4nd) ([raw file](https://github.com/bloombooks/bloomreader/blob/6e6ff7d6677d4e521b6901d4b50cc550bd2fabfb/app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java#L112)):*
> ```Java
>         }
>         catch (JSONException e){
>             Log.e("Analytics", "Error processing deviceId file json.");
> ```

Let's include the exception message in the log. May give useful clues to what is wrong.

---

*[app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, line 123 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/59#-KxNtZaG44r3PIBsjSBv:-KxNtZaG44r3PIBsjSBw:b-3lamf8) ([raw file](https://github.com/bloombooks/bloomreader/blob/6e6ff7d6677d4e521b6901d4b50cc550bd2fabfb/app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java#L123)):*
> ```Java
> 
>     private static void reportDeviceIdParseSuccess(String project, String device){
>         String successMessage = getBloomApplicationContext().getString(R.string.metadata_loaded) + "\nProject: " + project + "\nDevice: " + device;
> ```

This feels half-hearted. If we're going to make this localizable, the whole message should be, and we should use an appropriate Format routine to inject the project and device where the localizer wants them (with localized labels). Since we only expect this toast to be seen by (very likely English-speaking) technicians, not localizing any of it would also make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/59#-:-KxNvNsAKrVpD3jLXreb:bygsb2p)*

**Comment by rjconrad** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java, line 123 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/59#-KxNtZaG44r3PIBsjSBv:-KxrFJEWR4w6rJGZlMP0:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/6e6ff7d6677d4e521b6901d4b50cc550bd2fabfb/app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java#L123)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This feels half-hearted. If we're going to make this localizable, the whole message should be, and we should use an appropriate Format routine to inject the project and device where the localizer wants them (with localized labels). Since we only expect this toast to be seen by (very likely English-speaking) technicians, not localizing any of it would also make sense.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/59)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/59#-:-KxwyYjGTjqvWE9442WH:bnfp4nl)*

**Comment by JohnThomson** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/59)*

**Pull request merged**
