### PR TITLE
Fix the filename generated for a bloom book imported from the SD card root with the system file explorer

### PR DESCRIPTION
**Pull request by rjconrad**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/50)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, line 88 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/50#-KwAfq_yuM7Ga683RSKI:-KwAfq_yuM7Ga683RSKJ:b-ertx5y) ([raw file](https://github.com/bloombooks/bloomreader/blob/edde25384a44723f1d473f47d85e49a2f4ada1cf/app/src/main/java/org/sil/bloom/reader/BloomFileReader.java#L88)):*
> ```Java
>             path = bookUri.getPath();
>         if(path.endsWith(Book.BOOK_FILE_EXTENSION)){
>             int start = Math.max(path.lastIndexOf(File.separator), path.lastIndexOf(':')) + 1;
> ```

Probably this shows my ignorance of something, but I only know of macs using colons for separation. Please stick in a comment saying more than the PR summary does about how it gets in there and why we need to deal with this. Thx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/50)*

**Comment by rjconrad** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, line 88 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/50#-KwAfq_yuM7Ga683RSKI:-KwAjp8tD6MHj-rVlNIS:berluln) ([raw file](https://github.com/bloombooks/bloomreader/blob/edde25384a44723f1d473f47d85e49a2f4ada1cf/app/src/main/java/org/sil/bloom/reader/BloomFileReader.java#L88)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Probably this shows my ignorance of something, but I only know of macs using colons for separation. Please stick in a comment saying more than the PR summary does about how it gets in there and why we need to deal with this. Thx.
</blockquote></details>

Discovered this when importing a book from the root of an SD card (portable storage) using the system file explorer. Turns out the path was "9016-2308:Lazy Brother.bloomd". Since there weren't any '/'s in the path, my code took that whole path as the filename. Then BR crashed while trying to open it. I was surprised too; I would have expected a directory in /mnt or something like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/50)*

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, line 88 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/50#-KwAfq_yuM7Ga683RSKI:-KwAmd3Yb_F_3_ZgAFNO:b-6p4xa8) ([raw file](https://github.com/bloombooks/bloomreader/blob/edde25384a44723f1d473f47d85e49a2f4ada1cf/app/src/main/java/org/sil/bloom/reader/BloomFileReader.java#L88)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

Discovered this when importing a book from the root of an SD card (portable storage) using the system file explorer. Turns out the path was "9016-2308:Lazy Brother.bloomd". Since there weren't any '/'s in the path, my code took that whole path as the filename. Then BR crashed while trying to open it. I was surprised too; I would have expected a directory in /mnt or something like that.
</blockquote></details>

Ok, so put something like that in a comment. This PR won't be good documentation in the  future when someone is trying to figure out this code. Thx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/50)*

**Comment by rjconrad** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/BloomFileReader.java, line 88 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/50#-KwAfq_yuM7Ga683RSKI:-KwEaeuPbzu6JqXMO2pM:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/edde25384a44723f1d473f47d85e49a2f4ada1cf/app/src/main/java/org/sil/bloom/reader/BloomFileReader.java#L88)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ok, so put something like that in a comment. This PR won't be good documentation in the  future when someone is trying to figure out this code. Thx.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/50)*

**Pull request merged**
