### PR TITLE
Target Api 33, Android 13 (BL-11181)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/298)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks basically good, but a few comments I think are worth at least considering.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/298#-:-NBneYHG7sQqUUFX6LNz:bbjps1o)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`app/src/main/AndroidManifest.xml` line 315 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBnaAESAfHsgratPLWG:-NBnaAESAfHsgratPLWH:b4fgbat) ([raw file](https://github.com/bloombooks/bloomreader/blob/aa4a8ae74bc998286426deb130ca3234dc7b44ca/app/src/main/AndroidManifest.xml#L315)):*
> ```XML
> 
>     
>     
> ```

Do we somehow check whether WiFi is enabled, when the user asks to 'receive over WiFi'? The second one might be involved in starting to listen for Bloom editor sending stuff.
___
*[`app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java` line 362 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBnb5FBEeOHEEeFnvL3:-NBnb5FBEeOHEEeFnvL4:b-49ta8w) ([raw file](https://github.com/bloombooks/bloomreader/blob/aa4a8ae74bc998286426deb130ca3234dc7b44ca/app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java#L362)):*
> ```Java
>         int iColumn = cursor.getColumnIndex(column);
>         return iColumn >= 0 ? cursor.getLong(iColumn) : -1;
>     }
> ```

It's not obvious why these methods belong on Application. Is there a utils class we could use?
The names initially made me thing of getting a cursor...I was expecting a choice of String, Int, or Long  argument to somehow identify the cursor wanted. Maybe e.g. GetStringFromCursor{Column}?
___
*[`app/src/main/java/org/sil/bloom/reader/NeedNewerWebViewActivity.java` line 54 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBncKjF6b_tSRaj2T-B:-NBncKjF6b_tSRaj2T-C:b-hrqtuh) ([raw file](https://github.com/bloombooks/bloomreader/blob/aa4a8ae74bc998286426deb130ca3234dc7b44ca/app/src/main/java/org/sil/bloom/reader/NeedNewerWebViewActivity.java#L54)):*
> ```Java
>         int mPendingIntentId = 123456;
>         int flags = PendingIntent.FLAG_CANCEL_CURRENT;
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
> ```

But since we now do (and soon must) target S, why do we need the test?
I can't make any useful sense of the documentation for this flag.  Clearly immutable is preferred, and in some contexts safer, but I have only the vaguest idea either why it is safer or why mutability might be needed. If you have acquired any useful understanding of it, a comment indicating why you don't think mutability is needed would be nice. If you just tried immutable because one or the other is required, that is preferred, and it seems to work, even that is worth saying, I think.
___
*[`app/src/main/res/raw/about_reader.txt` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBne5E89UAtSO24b_m6:-NBne5E89UAtSO24b_m7:b-qop3mz) ([raw file](https://github.com/bloombooks/bloomreader/blob/f37ac26dd22147585cfe5b0b503af8e0e4a184df/app/src/main/res/raw/about_reader.txt#L13)):*
> ```help
> Book arrival sound: "You've Been Informed", CC-BY, notificationsounds.com.
> Right answer sound: "Oh, Finally", CC-BY, notificationsounds.com.
> Wrong answer sound: "Out of Bounds", CC-BY, notificationsounds.com.
> ```

Why don't we need these any more? (I would expect them to come bundled with BloomPlayer.)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/298)* status: 5 of 12 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`app/src/main/AndroidManifest.xml` line 315 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBnaAESAfHsgratPLWG:-NByUjnVBGHSa2mqTX2H:b-pa551e) ([raw file](https://github.com/bloombooks/bloomreader/blob/aa4a8ae74bc998286426deb130ca3234dc7b44ca/app/src/main/AndroidManifest.xml#L315)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do we somehow check whether WiFi is enabled, when the user asks to 'receive over WiFi'? The second one might be involved in starting to listen for Bloom editor sending stuff.
</blockquote></details>

I'm not sure. I figured it was best just to leave them in
___
*[`app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java` line 362 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBnb5FBEeOHEEeFnvL3:-NByTcC38Kf2aaOHFjdh:bi7y9r7) ([raw file](https://github.com/bloombooks/bloomreader/blob/aa4a8ae74bc998286426deb130ca3234dc7b44ca/app/src/main/java/org/sil/bloom/reader/BloomReaderApplication.java#L362)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious why these methods belong on Application. Is there a utils class we could use?
The names initially made me thing of getting a cursor...I was expecting a choice of String, Int, or Long  argument to somehow identify the cursor wanted. Maybe e.g. GetStringFromCursor{Column}?
</blockquote></details>

I couldn't think of or find a better place, but I also wasn't excited about putting them there. 
Now I've created CommonUtilities. What do you think?
___
*[`app/src/main/java/org/sil/bloom/reader/NeedNewerWebViewActivity.java` line 54 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBncKjF6b_tSRaj2T-B:-NByRjDJCB-J2uxW3nlU:b-qz6t12) ([raw file](https://github.com/bloombooks/bloomreader/blob/aa4a8ae74bc998286426deb130ca3234dc7b44ca/app/src/main/java/org/sil/bloom/reader/NeedNewerWebViewActivity.java#L54)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

But since we now do (and soon must) target S, why do we need the test?
I can't make any useful sense of the documentation for this flag.  Clearly immutable is preferred, and in some contexts safer, but I have only the vaguest idea either why it is safer or why mutability might be needed. If you have acquired any useful understanding of it, a comment indicating why you don't think mutability is needed would be nice. If you just tried immutable because one or the other is required, that is preferred, and it seems to work, even that is worth saying, I think.
</blockquote></details>

I tried to explain...
___
*[`app/src/main/res/raw/about_reader.txt` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBne5E89UAtSO24b_m6:-NByQybT6CQUmqJphSGR:bny1tlh) ([raw file](https://github.com/bloombooks/bloomreader/blob/f37ac26dd22147585cfe5b0b503af8e0e4a184df/app/src/main/res/raw/about_reader.txt#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why don't we need these any more? (I would expect them to come bundled with BloomPlayer.)
</blockquote></details>

Hm. I actually assumed this was cruft from when the sounds were actually part of BR.
And I assumed the sound files we use now were different.
But the sound files are still the same...

So... 
The general question is whether or not this file should include credits for stuff in bloom-player. If not, we can remove these. If so, there are probably other things to add.
It kind of feels like this should just have a link to the bloom-player project. And that project should credits things itself. Otherwise, you'll always play the game of trying to keep two lists up to date. Thoughts?

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/298#-:-NCfBwJB5s-GA1Dol2si:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`app/src/main/res/raw/about_reader.txt` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBne5E89UAtSO24b_m6:-NCfAIlc4eNocFyp2uGx:b-l21qxs) ([raw file](https://github.com/bloombooks/bloomreader/blob/f37ac26dd22147585cfe5b0b503af8e0e4a184df/app/src/main/res/raw/about_reader.txt#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. I actually assumed this was cruft from when the sounds were actually part of BR.
And I assumed the sound files we use now were different.
But the sound files are still the same...

So... 
The general question is whether or not this file should include credits for stuff in bloom-player. If not, we can remove these. If so, there are probably other things to add.
It kind of feels like this should just have a link to the bloom-player project. And that project should credits things itself. Otherwise, you'll always play the game of trying to keep two lists up to date. Thoughts?
</blockquote></details>

I agree, maintaining duplicate lists is annoying (and not just two...by the same argument BP assets should be credited by all its clients).

But BP is hardly ever the top-level thing. It doesn't have its own About box where its credits could be seen. So just leaving them in some BP source file doesn't feel quite fair to the authors who asked us to credit their work.

So it makes sense to go ahead and remove them for this PR. But maybe we should think about some mechanism for BP to publish its credits information in a form that clients could append to their own? We have some mechanisms for cross-iframe communication already, so maybe we could just add a case for requesting a chunk of HTML that BP would like inserted into the client app's credits?

**Comment by andrew-polk** [comment]
*[`app/src/main/res/raw/about_reader.txt` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/298#-NBne5E89UAtSO24b_m6:-NCfKG0OD_3eX8R8Si88:b-5dor8h) ([raw file](https://github.com/bloombooks/bloomreader/blob/f37ac26dd22147585cfe5b0b503af8e0e4a184df/app/src/main/res/raw/about_reader.txt#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I agree, maintaining duplicate lists is annoying (and not just two...by the same argument BP assets should be credited by all its clients).

But BP is hardly ever the top-level thing. It doesn't have its own About box where its credits could be seen. So just leaving them in some BP source file doesn't feel quite fair to the authors who asked us to credit their work.

So it makes sense to go ahead and remove them for this PR. But maybe we should think about some mechanism for BP to publish its credits information in a form that clients could append to their own? We have some mechanisms for cross-iframe communication already, so maybe we could just add a case for requesting a chunk of HTML that BP would like inserted into the client app's credits?
</blockquote></details>

Ok, I'll bring it up. For now, I've added bloom-player here so people can at least have a pointer there.

**Review by JohnThomson — APPROVED** [review]
I'm happy with your intentional changes, but somehow my analytics changes have gotten into this PR also. It would be better not to have them, or at least, you should check that the merge isn't going to make conflicts.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/298#-:-NDjHAP-7Z9dradR0t7v:bxctg9s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Comment by andrew-polk** [comment]
Reviewable is just confused as to how to display things since the first version of the PR was before I rebased on your changes.
So my PR isn't actually bringing in your changes. This can only be seen by looking at the changes as a whole again.

**Pull request merged**
