### PR TITLE
Refresh list (and notify) when a new book arrives (BL-4755)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/9)

### CODE REVIEW

**Comment by JohnThomson** [comment]
For the WiFi, this would be more complexity than we need...WiFi is going to have a specific activity for receiving books, and we could simply refresh the list whenever the main activity is resumed. (At least I'm pretty sure there's an event that happens whenever it's brought to the foreground.) But maybe usb push can happen any time and will stay that way?
Other than that, basically looks good. Various questions, probably don't need a response, just checking you've thought of things.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 53 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8xZ-WSkhpyOsv9Ogs:-Kq8xZ-XYAwNHzHmgCMU:bj83fgt) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/AndroidManifest.xml#L53)):*
> ```XML
>                 <data
>                     android:mimeType="application/octet-stream"
>                     android:scheme="content" />
> ```

What are we doing with email? (Maybe this was just boilerplate that got reformatted?)

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 41 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8ybsF5q6osoWjmGGV:-Kq8ybsF5q6osoWjmGGW:b-n9gdqt) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L41)):*
> ```Java
>     @Override
>     public void onDestroy() {
>         stopObserving();
> ```

I suspect it would be good to stopObserving in onPause(?Suspend?...I don't think we need to get these notifications in the background, do we?) and resume in the inverse event.
This might require the main activity to refresh the list when brought to the foreground.

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 51 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8yK_lWAIbIt9Phn-r:-Kq8yK_lWAIbIt9Phn-s:bfywno4) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L51)):*
> ```Java
> 
>     private void startObserving() {
>         final String pathToWatch = BookCollection.getLocalBooksDirectory().getPath();
> ```

would it be worth calling stopWatching() here, or doing something to make sure there's no way to have two observers running or one that we never stop? Hopefully start and stop calls are nicely paired, but in case something goes wrong...

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 66 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8yCTyCwOO9-P4O9Zl:-Kq8yCTyCwOO9-P4O9Zm:b86myyw) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L66)):*
> ```Java
> 
>     private void stopObserving() {
>         observer.stopWatching();
> ```

Should we do anything else to dispose of it, since we won't use it again?

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 54 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zgKRc-jj_O0dkPc3:-Kq8zgKRc-jj_O0dkPc4:b-9w44km) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L54)):*
> ```Java
>                 String filePath = intent.getStringExtra(DirectoryChangeListenerService.DCLS_FILE_NAME_MESSAGE);
>                 Book book = _bookCollection.addBookIfNeeded(filePath);
>                 if (book != null) {
> ```

addBookIfNeeded() returns the book either way, but this is written assuming it only returns a new book.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 57 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq9-oerFA63MXIyMe8W:-Kq9-oerFA63MXIyMe8X:b-6e6gs) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L57)):*
> ```Java
>                     refreshList();
>                 }
>                 Toast.makeText(MainActivity.this, book.name + " added or updated", Toast.LENGTH_SHORT).show();
> ```

I wonder if this deserves a notification, so the user won't miss the fact that he's got a new book if he glances away...probably not, since he can only get new books if he plugs it in and explicitly sends, or by (eventually) launching the WiFi books activity. Anyway, seemed worth asking.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 103 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zLFzvOpgnbsPea8i:-Kq8zLFzvOpgnbsPea8j:b-5oycq2) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L103)):*
> ```Java
> 
>     @Override
>     protected void onStart() {
> ```

Again I wonder whether onPause/Resume would be more appropriate?

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 39 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zvsnJDfzw2E9x5N5:-Kq8zvsnJDfzw2E9x5N6:bzd02pu) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L39)):*
> ```Java
>     private Book addBook(String path) {
>         Book book = new Book(path);
>         _books.add(book);
> ```

I suppose they are automatically sorted somehow?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-:-Kq9-5HIkaP_LRmP8ZTF:b-lj7hll)*

**Comment by andrew-polk** [comment]
Yes, USB can send a book in and mode at any time. I don't anticipate that changing.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 53 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8xZ-WSkhpyOsv9Ogs:-Kq9XnGIxGoRp5AQjO3_:b-rk3uuf) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/AndroidManifest.xml#L53)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

What are we doing with email? (Maybe this was just boilerplate that got reformatted?)
</blockquote></details>

Yes, it just got moved by an auto-generator.

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 51 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8yK_lWAIbIt9Phn-r:-Kq9oUptUxLhwZ2LExg9:btp4ym2) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L51)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

would it be worth calling stopWatching() here, or doing something to make sure there's no way to have two observers running or one that we never stop? Hopefully start and stop calls are nicely paired, but in case something goes wrong...
</blockquote></details>

Good point. I'll fix it.

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 66 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8yCTyCwOO9-P4O9Zl:-Kq9oL-yeb2hxndBk6FL:b-3gborw) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L66)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should we do anything else to dispose of it, since we won't use it again?
</blockquote></details>

I'll take a look.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 54 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zgKRc-jj_O0dkPc3:-Kq9YmXqTIUibHwJVy4z:b-ekcbr2) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L54)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

addBookIfNeeded() returns the book either way, but this is written assuming it only returns a new book.
</blockquote></details>

Good point. That's leftover from one of several attempts to make this code make sense. I was really wishing java had out parameters. I'll figure out a better way...

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 57 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq9-oerFA63MXIyMe8W:-Kq9YJuHE5FQSWqxDyzr:bps6cgm) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L57)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I wonder if this deserves a notification, so the user won't miss the fact that he's got a new book if he glances away...probably not, since he can only get new books if he plugs it in and explicitly sends, or by (eventually) launching the WiFi books activity. Anyway, seemed worth asking.
</blockquote></details>

The design is to scroll the list and highlight the new book. When I do that, I will probably take this toast out. This is basically just a first step.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 103 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zLFzvOpgnbsPea8i:-Kq9nuWQO_VVpAcO1rc7:b-6cpmps) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L103)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again I wonder whether onPause/Resume would be more appropriate?
</blockquote></details>

I want it to start when MainActivity starts and run whenever the app is up because the design says to navigate to the list view (another piece I have yet to implement). But I'll look into what this current code means for when the app is in the background. Good thought.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 39 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zvsnJDfzw2E9x5N5:-Kq9YUvT2XoumkaFxb_q:b-mqw18a) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L39)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose they are automatically sorted somehow?
</blockquote></details>

Isn't currently sorted, so I'll create a card for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-:-Kq9XdTgFCnWzxxGzC1c:bhygr6a)*

**Comment by JohnThomson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 103 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zLFzvOpgnbsPea8i:-Kq9tFADtgMJlRuX5XNb:bx51789) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L103)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I want it to start when MainActivity starts and run whenever the app is up because the design says to navigate to the list view (another piece I have yet to implement). But I'll look into what this current code means for when the app is in the background. Good thought.
</blockquote></details>

I don't recall details, but there are probably notifications for the whole app becoming active and not, device power down and up...I saw recently that there's even one for low battery, which we could use if there's anything we can suspend...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/9)*

**Comment by andrew-polk** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 103 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zLFzvOpgnbsPea8i:-KqYHcyyl7NgkihaW0uY:b-canogb) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L103)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't recall details, but there are probably notifications for the whole app becoming active and not, device power down and up...I saw recently that there's even one for low battery, which we could use if there's anything we can suspend...
</blockquote></details>

Reworked and simplified.

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 41 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8ybsF5q6osoWjmGGV:-KqYHWppKv6NFby6Pi9Y:b-canogb) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L41)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suspect it would be good to stopObserving in onPause(?Suspend?...I don't think we need to get these notifications in the background, do we?) and resume in the inverse event.
This might require the main activity to refresh the list when brought to the foreground.
</blockquote></details>

Reworked and simplified.

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 51 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8yK_lWAIbIt9Phn-r:-KqYHRV97_wU7a9E_rWd:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Good point. I'll fix it.
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java, line 66 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8yCTyCwOO9-P4O9Zl:-KqYHTZVEHLliQcGfzkE:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/DirectoryChangeListenerService.java#L66)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'll take a look.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/9)*

**Comment by JohnThomson** [comment]
A few thoughts that don't fit anywhere in particular in the code:
- since we're now doing the observer only while one of our activities is active, do we need the main activity to refresh the list in OnResume, in case a book was downloaded while BR wasn't active (which I think is possible with USB)?
- if we do that do we still need to observe the directory? I suppose that's the only way we detect new books while we ARE active?
- should we be persisting the Application data somehow? (Note that a lot of stuff gets destroyed and re-created by just  rotating the phone.)
(do we need cards for saving state like was a book open, which one, what page?)

---

Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/BaseActivity.java, line 9 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYWYtfpK2x4uaCxpxN:-KqYWYtgYO-z0M6DaFw8:byx5iv7) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/BaseActivity.java#L9)):*
> ```Java
> import org.sil.bloom.reader.models.BookCollection;
> 
> // A base abstract class which every activity should extend
> ```

Sort of feels like too little functionality to impose such a strong constraint on all future activity development. But I don't see a better alternative. If we some day need an Activity with a different base class, we can refactor into something each client can hook into...but using it will involve remembering to do something in several places.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 94 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYXUiobd2IPLXkq_Cg:-KqYXUiobd2IPLXkq_Ch:b38xvfe) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L94)):*
> ```Java
>         if (bookToHighlight != null) {
>             updateForNewBook(bookToHighlight);
>             ((BloomReaderApplication) this.getApplication()).setBookToHighlight(null);
> ```

Why null rather than bookToHighlight?

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 78 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYXw4ZRdub0WPv_1DU:-KqYXw4ZRdub0WPv_1DV:br0duw7) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L78)):*
> ```Java
>         // Clears the history so now the back button doesn't take from the main activity back to here.
>         intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
>         startActivity(intent);
> ```

Won't finish() automatically take us back to main? Or is that state lost if the OS unloads and restarts the app?

---

*[app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java, line 89 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYY_k70fGXu9G1EeEV:-KqYY_k70fGXu9G1EeEW:bj74vq) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java#L89)):*
> ```Java
>     protected void onNewOrUpdatedBook(String fullPath) {
>         // Don't do anything.
>         // TODO: We'll want to update the main activity upon exit.
> ```

So, should this be done before merging? Or a card made?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-:-KqYYgY3E8dIq2SW8WQ8:b-w362el)*

**Comment by andrew-polk** [comment]
> since we're now doing the observer only while one of our activities is active, do we need the main activity to refresh the list in OnResume, in case a book was downloaded while BR wasn't active (which I think is possible with USB)?

Yes, good point. Done.

> I suppose that's the only way we detect new books while we ARE active?

Right.

> should we be persisting the Application data somehow? (Note that a lot of stuff gets destroyed and re-created by just rotating the phone.)
(do we need cards for saving state like was a book open, which one, what page?)

Treating as yagni for now.

---

Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/BaseActivity.java, line 9 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYWYtfpK2x4uaCxpxN:-KqZ1r4GwHgJUPgbSksu:b-fwi3pk) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/BaseActivity.java#L9)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sort of feels like too little functionality to impose such a strong constraint on all future activity development. But I don't see a better alternative. If we some day need an Activity with a different base class, we can refactor into something each client can hook into...but using it will involve remembering to do something in several places.
</blockquote></details>

I figure there is a strong likelihood this base class will get enhanced as we go.
And yes, I figured we can refactor later.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 94 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYXUiobd2IPLXkq_Cg:-KqZ26s32x0u86mnqAxB:b52xw46) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L94)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why null rather than bookToHighlight?
</blockquote></details>

null resets it to the state which means there is nothing to do (since we did what was needed).

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 78 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYXw4ZRdub0WPv_1DU:-KqZ2FrnwrFrKNMV5V23:b-9xvvfn) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L78)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Won't finish() automatically take us back to main? Or is that state lost if the OS unloads and restarts the app?
</blockquote></details>

My understanding is it just tells the current activity to finish up whatever it is doing (and be sure to call onDestroy()). I didn't test just calling finish. But you're probably right that if the app had been restarted, it wouldn't know where to go.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 39 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-Kq8zvsnJDfzw2E9x5N5:-KqZ3LjV2TG6ad3KJlV-:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/78ed6ebe2ffc9d5a595681d1099289b1703eed68/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't currently sorted, so I'll create a card for that.
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java, line 89 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-KqYY_k70fGXu9G1EeEV:-KqZ3MyITz3wPSd2BSZ6:b-8ds6xs) ([raw file](https://github.com/bloombooks/bloomreader/blob/27129040864ee6129a70364e18776c8051676aca/app/src/main/java/org/sil/bloom/reader/WiFi/GetFromWiFiActivity.java#L89)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So, should this be done before merging? Or a card made?
</blockquote></details>

I'll note it in the card I'm working on (which is incomplete as yet anyway). Someone else may have to implement this if I can't figure out how to get WiFi send/receive to work with the firewall.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-:-KqZ1YYD6lvGnKzf9Lu6:b-85qokg)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/9#-:-KqZMuAwgKdEH2h0QFlO:bnfp4nl)*

**Pull request merged**
