### PR TITLE
Merge 'JohnThomson/BL-4955analytics' with some improvements (BL-4956)

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/40)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 241 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/40#-KvYbqytPIapKWFD7uW1:-KvYbqytPIapKWFD7uW2:b829s1j) ([raw file](https://github.com/bloombooks/bloomreader/blob/fab9e13d916cce13ae6a85525e61cf02ea7ede9c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L241)):*
> ```Java
>             Analytics.with(BloomReaderApplication.getBloomApplicationContext()).track("Book opened", new Properties().putValue("title", mBookName));
>         } catch (Exception error) {
>             Toast.makeText(getApplicationContext(), "Error reporting load on "+path, Toast.LENGTH_SHORT).show();
> ```

I'm confused. Why would we want the user to see this?
Is this line left over after the VerboseToast one below was added to replace it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/40)*

**Comment by andrew-polk** [comment]
Supercedes #36

**Comment by hatton** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 241 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/40#-KvYbqytPIapKWFD7uW1:-KvYm66kpH8_lH1nrHD-:b-ffk6wm) ([raw file](https://github.com/bloombooks/bloomreader/blob/fab9e13d916cce13ae6a85525e61cf02ea7ede9c/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L241)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm confused. Why would we want the user to see this?
Is this line left over after the VerboseToast one below was added to replace it?
</blockquote></details>

SHouldn't be there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/40)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/40)*

**Pull request merged**
