### PR TITLE
First two stages of bookshelf support

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/53)

### CODE REVIEW

**Comment by gmartin7** [comment]
Well, I can say I've seen them all and nothing sticks out to me, anyway.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java, line 36 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/53#-Kwv1nA9lENtJ6CEmJq6:-Kwv1nAASIWvu1d71Uuk:b20u02g) ([raw file](https://github.com/bloombooks/bloomreader/blob/fc5556415e778ac1919f766f32be21cf8ed72984/app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java#L36)):*
> ```Java
> 
>     @Test
>     public void isBookInFilter_inShelf_sameFilter_True() throws Exception {
> ```

Do java tests always throw Exceptions, even when they return 'true' like this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/53#-:-Kwv2XJMKIkSxUR-PC0K:b2ihjpb)*

**Comment by andrew-polk** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/res/layout/book_list_content.xml, line 11 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/53#-Kwv2iwGvXBZXuEN5U4E:-Kwv2iwGvXBZXuEN5U4F:b-ckdx36) ([raw file](https://github.com/bloombooks/bloomreader/blob/fc5556415e778ac1919f766f32be21cf8ed72984/app/src/main/res/layout/book_list_content.xml#L11)):*
> big

bit (if there is a change to be made)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/53)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/53#-:-Kwv5OBi8CzwvPA2MSjd:bnfp4nl)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java, line 36 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/53#-Kwv1nA9lENtJ6CEmJq6:-Kwv5PltG9pDsIH7xg6t:b6rswo8) ([raw file](https://github.com/bloombooks/bloomreader/blob/fc5556415e778ac1919f766f32be21cf8ed72984/app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java#L36)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Do java tests always throw Exceptions, even when they return 'true' like this?
</blockquote></details>

This syntax essentially means "can throw Exception"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/53)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java, line 36 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/53#-Kwv1nA9lENtJ6CEmJq6:-KwvKJXHcoo39tXMtMKS:bcjnpt7) ([raw file](https://github.com/bloombooks/bloomreader/blob/fc5556415e778ac1919f766f32be21cf8ed72984/app/src/test/java/org/sil/bloom/reader/models/BookCollectionTest.java#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This syntax essentially means "can throw Exception"
</blockquote></details>

(which all unit tests can basically do, since that's how they fail)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/53)*

**Pull request merged**
