### PR TITLE
BL-4945 Build Bloom in multiple flavors

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/33)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/build.gradle, line 60 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/33#-KtGyzSBMxlHSgJXGRaB:-KtGyzSBMxlHSgJXGRaC:b-b0i1j3) ([raw file](https://github.com/bloombooks/bloomreader/blob/36874419e837813dc74274cea3dd81716df7afd6/app/build.gradle#L60)):*
> ```Gradle
>     }
> 
>     productFlavors {
> ```

How do we set this in the build? What is the default if we don't set it? 
It seems that this needs to also tie into the playAccountConfigs.

We also need to figure out how to have different Play Store metadata (BloomReader/app/src/main/play) for each flavor. I think the plugin (https://github.com/Triple-T/gradle-play-publisher) has some help with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/33)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/build.gradle, line 60 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/33#-KtGyzSBMxlHSgJXGRaB:-KtHHXKTV5FH5OhCajyo:b-ae5f0f) ([raw file](https://github.com/bloombooks/bloomreader/blob/36874419e837813dc74274cea3dd81716df7afd6/app/build.gradle#L60)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How do we set this in the build? What is the default if we don't set it? 
It seems that this needs to also tie into the playAccountConfigs.

We also need to figure out how to have different Play Store metadata (BloomReader/app/src/main/play) for each flavor. I think the plugin (https://github.com/Triple-T/gradle-play-publisher) has some help with that.
</blockquote></details>

There is probably a way to build just one flavor, but the default is to build them all, that is, you currently get I think six apks. The build just needs to publish the one it wants.
I can look into the metadata thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/33)*

**Comment by andrew-polk** [comment]
*[app/build.gradle, line 60 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/33#-KtGyzSBMxlHSgJXGRaB:-KtHJZa3za0RGaL9LO9C:b-4poubv) ([raw file](https://github.com/bloombooks/bloomreader/blob/36874419e837813dc74274cea3dd81716df7afd6/app/build.gradle#L60)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There is probably a way to build just one flavor, but the default is to build them all, that is, you currently get I think six apks. The build just needs to publish the one it wants.
I can look into the metadata thing.
</blockquote></details>

Ok, got it. So we also need to make sure the gradle-play-publisher is going to push the correct apk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/33)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/33#-:-KtIF1Kcs1uEqI6DDOgx:bnfp4nl)*

**Pull request merged**
