### PR TITLE
Ship and use Andika rather than ANB (BL-11259)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/287)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good. A few minor suggestions.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/287#-:-N6mZ2h_8kix617ch1l5:bi85p69)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`app/src/main/assets/book support files/assets.css` line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mXeMb-qhSEJdom3CE:-N6mXeMb-qhSEJdom3CF:betk8zf) ([raw file](https://github.com/bloombooks/bloomreader/blob/a7b8a01928c0d82768dc5f076766eb79804ddbcd/app/src/main/assets/book%20support%20files/assets.css#L1)):*
> ```CSS
> /* this should be included by books, to link up any fonts and other assets that are built
> ```

Since this file is deleted, I'm a bit surprised not to see deletion of some code that inserts it into the book either here or in the parallel change in Bloom Player. Maybe I missed it?
___
*[`app/src/main/assets/book support files/assets.css` line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mW6cW9hKi9xmx0hN-:-N6mW6cW9hKi9xmx0hN0:b-h1ldy7) ([raw file](https://github.com/bloombooks/bloomreader/blob/a7b8a01928c0d82768dc5f076766eb79804ddbcd/app/src/main/assets/book%20support%20files/assets.css#L21)):*
> ```CSS
> span.ui-audioCurrent,.ui-audioCurrent p {
>     background-color: yellow
> }
> ```

Sure we don't need this any more? I don't see it reappearing anywhere, though the comment was not very helpful in understanding why it was ever needed.
___
*[`app/src/main/assets/book support files/assets.css` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mVs-O1LGEncYwj1XD:-N6mVs-O1LGEncYwj1XE:bcd7p6y) ([raw file](https://github.com/bloombooks/bloomreader/blob/a7b8a01928c0d82768dc5f076766eb79804ddbcd/app/src/main/assets/book%20support%20files/assets.css#L36)):*
> ```CSS
> *[tabindex]:focus {
>     outline: none;
> }
> ```

Sure we don't need this any more? I don't see it reappearing anywhere.
___
*[`app/src/main/java/org/sil/bloom/reader/ReaderWebViewClient.java` line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mWPlrDMOd1tMtqc7J:-N6mWPlrDMOd1tMtqc7K:b44zsd2) ([raw file](https://github.com/bloombooks/bloomreader/blob/85593934ddbf137917d0c85f911405ff4c54ee40/app/src/main/java/org/sil/bloom/reader/ReaderWebViewClient.java#L58)):*
> ```Java
>         try {
>             if (!url.contains("/host/fonts/"))
>                 return null;
> ```

I could not imagine why an HTML document that presumably has something like font-family: Andika should result in a URL that contains /host/fonts when no font-face declaration obviously applies (until I found the font-face trick in the parallel BP PR), so maybe a brief explanation would help others too?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/287)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`app/src/main/assets/book support files/assets.css` line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mXeMb-qhSEJdom3CE:-N6nQpo_BFSgr-Nva1Lg:b-op9m6l) ([raw file](https://github.com/bloombooks/bloomreader/blob/a7b8a01928c0d82768dc5f076766eb79804ddbcd/app/src/main/assets/book%20support%20files/assets.css#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since this file is deleted, I'm a bit surprised not to see deletion of some code that inserts it into the book either here or in the parallel change in Bloom Player. Maybe I missed it?
</blockquote></details>

Sorry; I meant to add a comment in reviewable stating that I couldn't find any code in BD, BR, or b-p which reference this file and therefore determined it must have been part of the old BloomPlayer/BR system.
___
*[`app/src/main/assets/book support files/assets.css` line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mW6cW9hKi9xmx0hN-:-N6nR0qOExtniHCPZotT:b-otilcs) ([raw file](https://github.com/bloombooks/bloomreader/blob/a7b8a01928c0d82768dc5f076766eb79804ddbcd/app/src/main/assets/book%20support%20files/assets.css#L21)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sure we don't need this any more? I don't see it reappearing anywhere, though the comment was not very helpful in understanding why it was ever needed.
</blockquote></details>

See comment above.
___
*[`app/src/main/assets/book support files/assets.css` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mVs-O1LGEncYwj1XD:-N6nR3_WD1eWbD4RMmFx:b-otilcs) ([raw file](https://github.com/bloombooks/bloomreader/blob/a7b8a01928c0d82768dc5f076766eb79804ddbcd/app/src/main/assets/book%20support%20files/assets.css#L36)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sure we don't need this any more? I don't see it reappearing anywhere.
</blockquote></details>

See comment above.
___
*[`app/src/main/java/org/sil/bloom/reader/ReaderWebViewClient.java` line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/287#-N6mWPlrDMOd1tMtqc7J:-N6nYYwE1PB06R-X1aEL:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/85593934ddbf137917d0c85f911405ff4c54ee40/app/src/main/java/org/sil/bloom/reader/ReaderWebViewClient.java#L58)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I could not imagine why an HTML document that presumably has something like font-family: Andika should result in a URL that contains /host/fonts when no font-face declaration obviously applies (until I found the font-face trick in the parallel BP PR), so maybe a brief explanation would help others too?
</blockquote></details>

Done.

**Comment by andrew-polk** [comment]
I think this is now ready for merge (not draft).

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
