### PR TITLE
BL-4972 Lock Wifi during file transfer

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/62)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java, line 39 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/62#-Kxibw7PAGSDc6MHAgb6:-Kxibw7PAGSDc6MHAgb7:bq6xxwj) ([raw file](https://github.com/bloombooks/bloomreader/blob/7ec52e633f6044877b490524926a67c1d5fec533/app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java#L39)):*
> ```Java
>     public void onDestroy() {
>         _server.stopThread();
>         _lock.release();
> ```

I guess we create and destroy a service whenever we enter the wifi activity? Otherwise, this would lock the whole time the app is running, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/62)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java, line 39 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/62#-Kxibw7PAGSDc6MHAgb6:-Kxmh4B4XUgT_6zRfZWX:b-v792f1) ([raw file](https://github.com/bloombooks/bloomreader/blob/7ec52e633f6044877b490524926a67c1d5fec533/app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess we create and destroy a service whenever we enter the wifi activity? Otherwise, this would lock the whole time the app is running, right?
</blockquote></details>

That's right...I guess it might be worth a comment. I don't know whether we might lock it permanently if something interrupts the transfer...maybe we should have a timeout?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/62)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java, line 39 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/62#-Kxibw7PAGSDc6MHAgb6:-Kxnf0smjATb_pHfzUtL:b7c2m8f) ([raw file](https://github.com/bloombooks/bloomreader/blob/7ec52e633f6044877b490524926a67c1d5fec533/app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java#L39)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That's right...I guess it might be worth a comment. I don't know whether we might lock it permanently if something interrupts the transfer...maybe we should have a timeout?
</blockquote></details>

Worth a few minutes of thought. But I wouldn't have a problem merging as is, I don't think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/62)*

**Comment by JohnThomson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java, line 39 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/62#-Kxibw7PAGSDc6MHAgb6:-Kxs4OlqY91aDvmjxXwm:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/7ec52e633f6044877b490524926a67c1d5fec533/app/src/main/java/org/sil/bloom/reader/WiFi/SyncService.java#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Worth a few minutes of thought. But I wouldn't have a problem merging as is, I don't think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/62)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/62#-:-Kxs7TNZf0GXPItKj9ic:bnfp4nl)*

**Pull request merged**
