### PR TITLE
Add signing support

### PR DESCRIPTION
**Pull request by chrisvire**
* use 'clean assembleRelease' target to build app
* define environment variable in build agent to pull values
  * BLOOM_READER_STORE_FILE
  * BLOOM_READER_STORE_PASSWORD
  * BLOOM_READER_KEY_ALIAS
  * BLOOM_READER_KEY_PASSWORD

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/25)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: as long as we have a sufficiently secure way to get the passwords into the environment variables. But I'm no security expert, probably someone else should take a look.
One thing that occurs to me is that anyone who can run any task on the build agent can presumably make a build step to echo %BLOOM_READER_STORE_PASSWORD% and get it into the log and see it. So we're trusting everyone who can make and run tasks. Hopefully that doesn't include 'guest'.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/25#-:-KsKnT_wXCyLLro4JAn8:b9nw8p4)*

**Comment by chrisvire** [comment]
After @andrew-polk and I got this working, then we were wondering about how these environment variable will be visible in TeamCity.  It might not be any better than specifying them in configuration parameters (like keyman does).

I think @andrew-polk is going to look into reading the parameters from a file instead of environment

**Comment by JohnThomson** [comment]
I suppose you've seen https://developer.android.com/studio/publish/app-signing.html#secure-shared-keystore? Where it says how to put the signing information in a file?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/25#-:-KsL3Kv0SN5hAfdBPCWj:b-8xtlhj)*

**Comment by andrew-polk** [comment]
Sorry; I can't modify this, so I have to create another PR.
Closing. Superceded by #26.

**Pull request closed without merging**
