### PR TITLE
BL-4883 speed up opening book

### PR DESCRIPTION
**Pull request by JohnThomson**
Basic display of animation while loading.
Make browsers for pages lazily
Make their contents just hold a single page.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/18)

### CODE REVIEW

**Comment by hatton** [comment]
Just some naming questions, but it would be good to get @andrew-polk to look for a more detailed review.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 219 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5UpOJ5j8qbqArtcPb:-Ks5UpOJ5j8qbqArtcPc:bd03zw7) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L219)):*
> ```Java
>     private class BookPagerAdapter extends PagerAdapter {
> 
>         private List<String> mPages;
> ```

It'd be good if this name told me if these strings are id's, or Html content, or whatever.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 220 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5W0IdCLWyCbgDGUGw:-Ks5W0IdCLWyCbgDGUGx:b-8bp7ej) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L220)):*
> ```Java
> 
>         private List<String> mPages;
>         private String mStartFrame;
> ```

I can't tell what "frames" are from a casual reading of this file. I'm guessing it's like html/body.  A better name or comment would be good. Maybe "htmlBeforePageContent"?

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 225 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5UbZcOX_Z-SnK6Arb:-Ks5UbZcOX_Z-SnK6Arc:b-qxru1e) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L225)):*
> ```Java
>         File mBookHtmlPath;
>         String mFolderPath;
>         WebView mNextPage;
> ```

The name here could be improved... above "mPages" is a string, but here "mNextPage" is a WebView.  Maybe something like "mNextPageBrowser"?

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 233 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5V5xjBtKWvVYpG3cz:-Ks5V5xjBtKWvVYpG3d-:bumxbbx) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L233)):*
> ```Java
> 
>         BookPagerAdapter(List<String> pages, ReaderActivity parent, File bookHtmlPath, String startFrame, String endFrame, String folderPath) {
>             mPages = pages;
> ```

As above, what does it mean for a page to be a string? I'm guessing html, but i don't know yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-:-Ks5W_i8SVP4er86R3x1:bzi64q3)*

**Comment by JohnThomson** [comment]
OK, I've attempted to improve the names. Will wait for Andrew before merging.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 219 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5UpOJ5j8qbqArtcPb:-KsAIdxMXg644eNmab6q:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L219)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It'd be good if this name told me if these strings are id's, or Html content, or whatever.
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 220 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5W0IdCLWyCbgDGUGw:-KsAIdMj54Kh9VReaSuM:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L220)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I can't tell what "frames" are from a casual reading of this file. I'm guessing it's like html/body.  A better name or comment would be good. Maybe "htmlBeforePageContent"?
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 225 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5UbZcOX_Z-SnK6Arb:-KsAId32qnemY0gOra_3:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L225)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The name here could be improved... above "mPages" is a string, but here "mNextPage" is a WebView.  Maybe something like "mNextPageBrowser"?
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 233 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-Ks5V5xjBtKWvVYpG3cz:-KsAIcJSAouPHo8s_H_u:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/9d18bc6cbb38d205a73b927ffb0e329c4e6200a9/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L233)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

As above, what does it mean for a page to be a string? I'm guessing html, but i don't know yet.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-:-KsAIi8iQgZl_xWep9W6:b-ijdmfp)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 182 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-KsFNz4aeKYMaK7AU4Kz:-KsFNz4bME2u_ssizE-x:b-n8dvfs) ([raw file](https://github.com/bloombooks/bloomreader/blob/2355c4b86624ee4180d72a2d375b43fc6a46d48a/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L182)):*
> ```Java
>         // For efficiency we assume a simple class attribute delimited with double quote.
>         // If this is in doubt we will need to either improve Bloom to enforce it
>         // or make this code smarter. But I think it's how Tidy formats things.
> ```

I'm pretty scared of the idea that other applications (Story Producer App) will be generating Bloom books, but that affects much more than just this, and I guess we will get there when we get there...

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 261 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-KsFPI4c8b6yPhkChzUk:-KsFPI4c8b6yPhkChzUl:bi9v1bn) ([raw file](https://github.com/bloombooks/bloomreader/blob/2355c4b86624ee4180d72a2d375b43fc6a46d48a/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L261)):*
> ```Java
> 
>             WebView browser = null;
>             synchronized (this) { // lock all access to these two variables.
> ```

Which two?
Is there any way to enforce this for future code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 182 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-KsFNz4aeKYMaK7AU4Kz:-KsFRXDMgiwIqJ5hiEl0:bgvmsf4) ([raw file](https://github.com/bloombooks/bloomreader/blob/2355c4b86624ee4180d72a2d375b43fc6a46d48a/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L182)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty scared of the idea that other applications (Story Producer App) will be generating Bloom books, but that affects much more than just this, and I guess we will get there when we get there...
</blockquote></details>

We could plausibly use a regular expression to make it more robust. I'll see what I can do.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 261 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-KsFPI4c8b6yPhkChzUk:-KsFR47MlbbmgoMjv3iv:b-fyd7wq) ([raw file](https://github.com/bloombooks/bloomreader/blob/2355c4b86624ee4180d72a2d375b43fc6a46d48a/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Which two?
Is there any way to enforce this for future code?
</blockquote></details>

The two (member) variables accessed in the synchronized block.
I'll think about a better way of enforcing it.
Another idea is just to drop this optimization. It was done before the single-page-content one, and may not be necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18)*

**Comment by andrew-polk** [comment]
*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 261 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-KsFPI4c8b6yPhkChzUk:-KsFS0OIkE1x_WRVsE_i:b-oodyjy) ([raw file](https://github.com/bloombooks/bloomreader/blob/2355c4b86624ee4180d72a2d375b43fc6a46d48a/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L261)):*
> The two (member) variables

Yes, of course. Silly me.

> Another idea is just to drop this optimization.

I'll leave that up to you. You've already optimized it at this point. But if you think it isn't helping, simplifying is good, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18)*

**Comment by andrew-polk** [comment]
I don't want to hold this up any longer, but it seems the logic to find the page divs and create html documents with just one page should be testable. Thoughts?
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-:-KsFeKcSRwea8qa3yJ8i:b-umrd42)*

**Comment by JohnThomson** [comment]
I agree, but setting up a unit testing framework is not a change that should be part of another task. Based on my experience with HTA, it's nontrivial...both the actual setup and the refactoring that is probably necessary.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-:-KsFtTEgyM2z9rUIyUcI:b-9ds3ts)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 261 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-KsFPI4c8b6yPhkChzUk:-KsFtqqKpD4KwXy51JLm:b-yzq2je) ([raw file](https://github.com/bloombooks/bloomreader/blob/2355c4b86624ee4180d72a2d375b43fc6a46d48a/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> The two (member) variables

Yes, of course. Silly me.

> Another idea is just to drop this optimization.

I'll leave that up to you. You've already optimized it at this point. But if you think it isn't helping, simplifying is good, too.
</blockquote></details>

Decided to keep it. There may be phones out there with performance poor enough to benefit. My test phones are fairly nice (though not quite state-of-the-art).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18)*

**Comment by andrew-polk** [comment]
Framework is there for very basic tests as this one would be. But you are correct it would require a little refactoring.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/18#-:-KsJTINdu3jQ2c4txOSq:b-mh4v2x)*

**Pull request merged**
