### PR TITLE
BL-4765 Show book thumbnails in list

### PR DESCRIPTION
**Pull request by rjconrad**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/60)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I like the idea of caching the thumbnails so we don't have to extract every book every time we display the list. However, what happens if the user updates a book (replaces it with a newer version) and the thumbnail has changed?

A process note: PR summary and commits should have the issue number (e.g. "BL-4765") in them so they get automatically tied to the issue. 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-KxSpu5GNEYyKK4jcVql:-KxSpu5GNEYyKK4jcVqm:b-h9waex) ([raw file](https://github.com/bloombooks/bloomreader/blob/0b2b3f52cf6b5ebffa97e467486926fc965fcd6b/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L30)):*
> .thumbs

What's the reason for starting this directory with a dot but not the no-thumbs directory?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-:-KxSqAYw94OokOnKlSqr:b-56kdmc)*

**Comment by rick-conrad-sil** [comment]
Ok, how about if I compare timestamps on the cached thumbnail and the .bloomd file?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-KxSpu5GNEYyKK4jcVql:-KxSxYvIWnM_OKAyzpNS:bw7c4qt) ([raw file](https://github.com/bloombooks/bloomreader/blob/0b2b3f52cf6b5ebffa97e467486926fc965fcd6b/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> .thumbs

What's the reason for starting this directory with a dot but not the no-thumbs directory?
</blockquote></details>

no-thumbs is inside .thumbs, so once you're already inside the hidden folder, it doesn't seem necessary to have the contents be hidden.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-:-KxSxPYPPJyCEeKBaVSn:b2yoh8y)*

**Comment by andrew-polk** [comment]
Makes sense. Thanks.
I guess you would have to do the same for the no-thumbs file.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/models/BookCollection.java, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-KxSpu5GNEYyKK4jcVql:-KxT57yzMI84B1d-_76L:b-7dg8kn) ([raw file](https://github.com/bloombooks/bloomreader/blob/0b2b3f52cf6b5ebffa97e467486926fc965fcd6b/app/src/main/java/org/sil/bloom/reader/models/BookCollection.java#L30)):*
<details><summary><i>Previously, rick-conrad-sil (Rick Conrad) wrote…</i></summary><blockquote>

no-thumbs is inside .thumbs, so once you're already inside the hidden folder, it doesn't seem necessary to have the contents be hidden.
</blockquote></details>

Got it; thanks. I didn't realize it was inside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-:-KxT5NmFX2vWkPFahMqO:b-7dpyv3)*

**Comment by rjconrad** [comment]
Now checks for a bloomd file that's newer than the cached thumbnail or no-thumb

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-:-KxrF3pwOESNoaOHiwfR:b-wy0f8c)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/60#-:-KxrZD7BBWcJo7y72byS:bnfp4nl)*

**Pull request merged**
