### PR TITLE
Leave it to Bloom Player to provide distribution info (BL-8898)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/282)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
Good idea. I will update it when the other gets merged.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/282#-:-N-ZPVG96KjfrHCXOwAO:bp1fcie)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/282#-:-N-cn8VX2D6wfHr-shvF:bb7f2mf)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
Approved. But did you see my suggestion in the card to test b-p change in BloomPUB viewer first?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/282#-:-N-coAPM30MpodrT8UAj:b-uarej4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
No. Will try.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/282#-:-N-dYbbg80kjLoRDD10L:b-44s7mf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
