### PR TITLE
Auto advance and play animations even if there are no "audio-sentence" spans anywhere in the book (BL-5771)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/128)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: with a couple of fairly unimportant questions

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 80 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/128#-LC5a1dM7b3PLt8ppZ9l:-LC5a1dN6f45qXcqq1Wp:b-g9czum) ([raw file](https://github.com/bloombooks/bloomreader/blob/01fd69031dfa8b09dd9baa409d95c200af16bf6f/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L80)):*
> ```Java
>     private static final Pattern sBodyPattern = Pattern.compile("<body [^>]*?>");
> 
>     private static final Pattern sAutoAdvance = Pattern.compile("data-bfautoadvance\\s*?=\\s*?\".*?\\bbloomReader\\b.*?\"");
> ```

If you change the first dot to [^\"] then if documents have auto-advance but not for BR it won't have to search the whole document. I suppose that's unlikely, though...

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 341 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/128#-LC5aWCQ1uvpVUvmIs07:-LC5aWCQ1uvpVUvmIs08:bw3f833) ([raw file](https://github.com/bloombooks/bloomreader/blob/01fd69031dfa8b09dd9baa409d95c200af16bf6f/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L341)):*
> ```Java
>         // Enhance: eventually also look for images with animation data?
>         
>         return sAutoAdvance.matcher(html).find() ||
> ```

We probably don't need to search the whole document for this...it's always on the body element or somewhere like that, isn't it, and we're already breaking the document up enough that we've probably found that.
Don't know whether this search takes enough time to matter, even on longish documents; just wondering. Don't optimize it unless you think it will make a useful difference.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/128#-:-LC5bDxu6ekU1OQeiLT7:b769yl6)*

**Comment by andrew-polk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 80 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/128#-LC5a1dM7b3PLt8ppZ9l:-LC5f8sgEhJ_SjCX7fzO:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/01fd69031dfa8b09dd9baa409d95c200af16bf6f/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L80)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If you change the first dot to [^\"] then if documents have auto-advance but not for BR it won't have to search the whole document. I suppose that's unlikely, though...
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 341 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/128#-LC5aWCQ1uvpVUvmIs07:-LC5eOSkDYUFAoqpLrp_:b516dym) ([raw file](https://github.com/bloombooks/bloomreader/blob/01fd69031dfa8b09dd9baa409d95c200af16bf6f/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L341)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We probably don't need to search the whole document for this...it's always on the body element or somewhere like that, isn't it, and we're already breaking the document up enough that we've probably found that.
Don't know whether this search takes enough time to matter, even on longish documents; just wondering. Don't optimize it unless you think it will make a useful difference.
</blockquote></details>

Decided I didn't think it was worth it. To "guarantee" a speed-up, we would need to pass the full html and a snippet to this method. Just felt messier.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/128)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 341 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/128#-LC5aWCQ1uvpVUvmIs07:-LC5jgkrCIRqkmlDIkpQ:b8r5ufn) ([raw file](https://github.com/bloombooks/bloomreader/blob/01fd69031dfa8b09dd9baa409d95c200af16bf6f/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L341)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Decided I didn't think it was worth it. To "guarantee" a speed-up, we would need to pass the full html and a snippet to this method. Just felt messier.
</blockquote></details>

Fair enough. Don't want messier, especially without definite evidence we need the performance gain.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/128#-:-LC5jqOEEy9OV1G4pK8I:bnfp4nl)*

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/128)*

**Pull request merged**
