### PR TITLE
BL-5101 show comprehension questions

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/71)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I didn't look super-detailed at the algorithms.
I have a couple higher-level thoughts:

-It doesn't feel right to rely so heavily on regex to glean information. If anything changes in our file structure, we could update BloomReader, but any older versions would not be able to read the data. This may be unavoidable (may have nothing to do with regex...), but I wanted to bring the issue up.
-I don't like seeing so much complex logic added to ReaderActivity. Can we extract much of this to a new class?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 412 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-KyWBbwkzGfO62BRuBs6:-KyWBbwkzGfO62BRuBs7:b-vatwwg) ([raw file](https://github.com/bloombooks/bloomreader/blob/6048102d80b8e0e30f51af26a73f3788f6a17b9b/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L412)):*
> JSONObject(json)

is this okay if json is null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-:-KyWCoHmoG7JHwlxObkB:bf0xt6y)*

**Comment by andrew-polk** [comment]
What did you think of my second point above? I don't want to create extra work, but it would be nice to keep the Activity code as clean as we reasonably can.

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 56 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-KyXfYzTj7BVozCUxHQC:-KyXfYzTj7BVozCUxHQD:b-jolt1l) ([raw file](https://github.com/bloombooks/bloomreader/blob/e451a6977833b761f02ee9fd3e294ce90d759133/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L56)):*
> ```Java
>     private static final Pattern sLayoutPattern = Pattern.compile("\\S+([P|p]ortrait|[L|l]andscape)\\b");
>     private static final Pattern sHeadElementEndPattern = Pattern.compile("</head");
>     private static final Pattern sQuestionClassPattern = Pattern.compile("<div [^>]*class=\"[^\"]*\\bquestions\\b");
> ```

I think all these regexs can be removed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-:-KyXfv4GE_4uJiLBvupl:bsckw3s)*

**Comment by JohnThomson** [comment]
Most of the messy testable logic has now moved to the desktop. The new code in ReaderActivity is pretty UI-focused. There's probably something here we could pull out into a model, but I'm not sure it would help.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 412 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-KyWBbwkzGfO62BRuBs6:-KyXrtrMeqKIDb2igCGi:bel5ds9) ([raw file](https://github.com/bloombooks/bloomreader/blob/6048102d80b8e0e30f51af26a73f3788f6a17b9b/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L412)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> JSONObject(json)

is this okay if json is null?
</blockquote></details>

Working on this I realized it was a waste. This activity is already passed the branding info to use in analytics.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 56 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-KyXfYzTj7BVozCUxHQC:-KyXrol2cUv7DdBIyP2l:b-5vu58u) ([raw file](https://github.com/bloombooks/bloomreader/blob/e451a6977833b761f02ee9fd3e294ce90d759133/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think all these regexs can be removed now.
</blockquote></details>

Done. (Except sMainLanguage is still used)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-:-KyXsU44ia0yMn1flPFO:bt1r54n)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 56 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-KyXfYzTj7BVozCUxHQC:-KypjRL16_1F4nbcZluZ:bqltutd) ([raw file](https://github.com/bloombooks/bloomreader/blob/e451a6977833b761f02ee9fd3e294ce90d759133/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L56)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. (Except sMainLanguage is still used)
</blockquote></details>

Is it possible you haven't published your latest changes? I'm not seeing code changes lining up with your last several comments (including that I still see these patterns here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/71)*

**Comment by JohnThomson** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 56 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-KyXfYzTj7BVozCUxHQC:-Kyplmwb4YNzNxPxagkP:b-sg4vz3) ([raw file](https://github.com/bloombooks/bloomreader/blob/e451a6977833b761f02ee9fd3e294ce90d759133/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it possible you haven't published your latest changes? I'm not seeing code changes lining up with your last several comments (including that I still see these patterns here.
</blockquote></details>

Sorry, yes, hadn't pushed latest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/71)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/71)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/71#-:-KypoxLYkpFux8VC4lkU:bnfp4nl)*

**Pull request merged**
