### PR TITLE
Wire up menu items (About Bloom, etc.) (BL-4917)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/29)

### CODE REVIEW

**Comment by andrew-polk** [comment]
*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 113 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/29#-KstVP1VGQrMImi2EKVc:-KstVP1VGQrMImi2EKVd:btznmma) ([raw file](https://github.com/bloombooks/bloomreader/blob/d24992425bbf8293315ecb51b91e4bf9ab7bc902/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L113)):*
> ```Java
>         try {
>             long start = System.currentTimeMillis();
>             BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(bookHtmlPath),"UTF-8"));
> ```

This logic was moved to IOUtilities

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/29)*

**Comment by hatton** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/IOUtilities.java, line 177 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/29#-Ksu90MbjBd-AlgfWl-g:-Ksu90MbjBd-AlgfWl-h:b-lugnjv) ([raw file](https://github.com/bloombooks/bloomreader/blob/f0054aea1df8dc81f0935e89d71f90c4571e4fca/app/src/main/java/org/sil/bloom/reader/IOUtilities.java#L177)):*
> ```Java
>     }
> 
>     public static String FileToString(File file) {
> ```

What would be the cons of adding a utility library like commons.io.IOUtils? ref https://stackoverflow.com/questions/12910503/read-file-as-string rather than continue to roll our own here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/29)*

**Comment by andrew-polk** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/IOUtilities.java, line 177 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/29#-Ksu90MbjBd-AlgfWl-g:-KsxXqve50hGb5mDTnR9:b-1uaqru) ([raw file](https://github.com/bloombooks/bloomreader/blob/f0054aea1df8dc81f0935e89d71f90c4571e4fca/app/src/main/java/org/sil/bloom/reader/IOUtilities.java#L177)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What would be the cons of adding a utility library like commons.io.IOUtils? ref https://stackoverflow.com/questions/12910503/read-file-as-string rather than continue to roll our own here?
</blockquote></details>

I can only think of the obvious cons:
- relying on a 3rd-party library (but this one shouldn't be an issue)
- possible increase in apk size, but our release apk should optimize out stuff it doesn't need

I didn't know about this library. I'll make a change for this code and we should try to use commons going forward, but I doubt we'll get away from our own utility class completely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/29)*

**Comment by andrew-polk** [comment]
*[app/build.gradle, line 81 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/29#-KsxZrgDTaPKHbuLifjW:-KsxZrgDTaPKHbuLifjX:b-srrbcm) ([raw file](https://github.com/bloombooks/bloomreader/blob/d24992425bbf8293315ecb51b91e4bf9ab7bc902/app/build.gradle#L81)):*
> ```Gradle
>     // Supports the WiFi module's 'server' used to receive books from Bloom desktop
>     compile 'cz.msebera.android:httpclient:4.4.1.2'
>     compile 'org.jsoup:jsoup:1.10.1'
> ```

Removing this was necessary to get the build to complete. I think it includes one or more files from apache commons, so there was a conflict.
We no longer use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/29)*

**Comment by andrew-polk** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/IOUtilities.java, line 177 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/29#-Ksu90MbjBd-AlgfWl-g:-KtHFMrTRdzoEO7Mzjm1:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/f0054aea1df8dc81f0935e89d71f90c4571e4fca/app/src/main/java/org/sil/bloom/reader/IOUtilities.java#L177)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I can only think of the obvious cons:
- relying on a 3rd-party library (but this one shouldn't be an issue)
- possible increase in apk size, but our release apk should optimize out stuff it doesn't need

I didn't know about this library. I'll make a change for this code and we should try to use commons going forward, but I doubt we'll get away from our own utility class completely.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/29)*

**Pull request merged**
