### PR TITLE
Open Book Detail link in external browser (BL-11409)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/295)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/295)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java` line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/295#-N9DRioE21KQkVgP8sMw:-N9DRioE21KQkVgP8sMx:bqy0y18) ([raw file](https://github.com/bloombooks/bloomreader/blob/da9f62ab22b5db8f76c04a59a9d4b9e66a3e4e55/app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java#L57)):*
> ```Java
>             // Open in external browser if not an app-hosted link (e.g. normal book detail page)
>             final Intent intent = new Intent(Intent.ACTION_VIEW, uri);
>             mOwner.startActivity(intent);
> ```

I'm not clear why the two lines above are needed. Doesn't returning true alone cause the link to open in the system browser?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/295)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java` line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/295#-N9DRioE21KQkVgP8sMw:-N9DzMsL3V3rv3vrmho8:biklhac) ([raw file](https://github.com/bloombooks/bloomreader/blob/da9f62ab22b5db8f76c04a59a9d4b9e66a3e4e55/app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java#L57)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear why the two lines above are needed. Doesn't returning true alone cause the link to open in the system browser?
</blockquote></details>

No, doc says, "returning true causes the current WebView to abort loading the URL, while returning false causes the WebView to continue loading the URL as usual."

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/295)* status: all files reviewed, 1 unresolved discussion

___
*[`app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java` line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/295#-N9DRioE21KQkVgP8sMw:-N9Yfrm-6JW1cRr1A8Yg:b-72vnob) ([raw file](https://github.com/bloombooks/bloomreader/blob/da9f62ab22b5db8f76c04a59a9d4b9e66a3e4e55/app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

No, doc says, "returning true causes the current WebView to abort loading the URL, while returning false causes the WebView to continue loading the URL as usual."
</blockquote></details>

Yes, but what happens next when the current WebView aborts loading the URL? When I didn't have this class at all, it used the system browser to open it instead, and I was guessing that's what happens after it aborts loading it in this one. Of course, not installing a WebViewClient at all may be different from either returning true or returning false.

Anyway, what you have apparently works, so I guess all is well.

**Comment by andrew-polk** [comment]
*[`app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java` line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/295#-N9DRioE21KQkVgP8sMw:-N9YhXca1ZeQ0l3oHzJ6:br94wt9) ([raw file](https://github.com/bloombooks/bloomreader/blob/da9f62ab22b5db8f76c04a59a9d4b9e66a3e4e55/app/src/main/java/org/sil/bloom/reader/BloomLibraryWebViewClient.java#L57)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, but what happens next when the current WebView aborts loading the URL? When I didn't have this class at all, it used the system browser to open it instead, and I was guessing that's what happens after it aborts loading it in this one. Of course, not installing a WebViewClient at all may be different from either returning true or returning false.

Anyway, what you have apparently works, so I guess all is well.
</blockquote></details>

I'm pretty sure I had tried it with just returning true and it didn't do anything.

**Pull request merged**
