### PR TITLE
[BL-5716] Improve performance by using ReyclerView for Book List

### PR DESCRIPTION
**Pull request by rjconrad**
https://silbloom.myjetbrains.com/youtrack/issue/BL-5716

This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/108)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm: but looks risky for a last-minute fix. Will discuss with JH.
Also awaiting UI review.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-:-L764HSlXyFEwfKRZRJI:b-6duxhl)*

**Comment by hatton** [comment]
> :lgtm: but looks risky for a last-minute fix. 

Oh drat, we *really* wanted this in for last saturday; I had thought it was in.

**Comment by JohnThomson** [comment]
Couple of minor suggestions, and I haven't really looked at BookAdapter yet, but I'm out of time for today...I'll give you what I have.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 54 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WIDM_uuFxAvAaffvd:-L7WIDM_uuFxAvAaffve:b-nacneh) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L54)):*
> ```Java
> 
>     private RecyclerView mBookRecyclerView;
>     private BookAdapter mBookAdapter;
> ```

Would mBookListAdapter be better? I find myself expecting this to be about adapting a single book.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 424 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WJBPC100mqchwJZzH:-L7WJBPDEdPSh3yLowDI:b89218) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L424)):*
> ```Java
>             // removes it from the collection.)
>             _bookCollection.deleteFromDevice(_bookCollection.getBookByPath(path));
>             // JT: without this an exception is thrown saying we should have called it.
> ```

This comment and the associated action may not apply now we're using a completely different class? If we still need to do it a different explanation may apply?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-:-L7WKFlJltC225Zly4ui:b-n12t86)*

**Comment by JohnThomson** [comment]
OK, I took a quick look at BookAdapter...one more request

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/BookAdapter.java, line 22 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WKwi3iBVjSnwYa9ld:-L7WKwi3iBVjSnwYa9le:b-ie122n) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/BookAdapter.java#L22)):*
> ```Java
> import java.util.List;
> 
> public class BookAdapter extends RecyclerView.Adapter<BookAdapter.ViewHolder> implements View.OnClickListener, View.OnLongClickListener {
> ```

Class comment? Describing how and where it is used in the overall architecture is very helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-:-L7WL6EeldnaIbfCBtK-:b-sm4egv)*

**Comment by rjconrad** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 54 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WIDM_uuFxAvAaffvd:-L7YL6uJxzFAzEYr9zNq:b5ws056) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L54)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Would mBookListAdapter be better? I find myself expecting this to be about adapting a single book.
</blockquote></details>

I think the same thought crossed my mind, but I forgot about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108)*

**Comment by rjconrad** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 424 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WJBPC100mqchwJZzH:-L7YLOeNZOiZBGWDdimn:b-h6t7w6) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L424)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This comment and the associated action may not apply now we're using a completely different class? If we still need to do it a different explanation may apply?
</blockquote></details>

I can just delete it. At least with the current implementation notifyDataSetChanged() is necessary and used every time we change the list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108)*

**Comment by rjconrad** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, line 22 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WKwi3iBVjSnwYa9ld:-L7YOhhr1SZxnkamwpY_:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/BookListAdapter.java#L22)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Class comment? Describing how and where it is used in the overall architecture is very helpful.
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 54 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WIDM_uuFxAvAaffvd:-L7YOnTD5eAsKybP4uJO:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L54)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

I think the same thought crossed my mind, but I forgot about it.
</blockquote></details>

Done.

---

*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 424 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7WJBPC100mqchwJZzH:-L7YOpRD9rLrj-j6oCRj:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/f42534b37594f635d7a8e237071c0ed24df863e7/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L424)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

I can just delete it. At least with the current implementation notifyDataSetChanged() is necessary and used every time we change the list.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108)*

**Comment by JohnThomson** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, line 38 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7ZnQ0-DuGv1pP9TRpC:-L7ZnQ0-DuGv1pP9TRpD:b-uci164) ([raw file](https://github.com/bloombooks/bloomreader/blob/ad41c989eafea9cc18289c811a8fb9c6d26daf00/app/src/main/java/org/sil/bloom/reader/BookListAdapter.java#L38)):*
> ```Java
> 
>     @Override
>     public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType){
> ```

Since these are overrides, you don't control the method names, but the terminology "ViewHolder" is not very obvious, nor is the term 'bind' in the method below. A comment outlining what this method and the following one are really about would help...what View does the holder hold? One row or several or all? In what way does it 'hold' it? When is Create called and when is Bind called?

---

*[app/src/main/java/org/sil/bloom/reader/BookListAdapter.java, line 65 at r2](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-L7ZmwDF4pZNgCuZpOaQ:-L7ZmwDGUFidO8bTtLiV:b1glgts) ([raw file](https://github.com/bloombooks/bloomreader/blob/ad41c989eafea9cc18289c811a8fb9c6d26daf00/app/src/main/java/org/sil/bloom/reader/BookListAdapter.java#L65)):*
> ```Java
>             }
>         } else {
>             holder.imageView.setBackgroundColor(Color.argb(0, 0, 0, 0));
> ```

This is a completely transparent color, right? Isn't there an existing named color you can use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108)*

**Comment by JohnThomson** [comment]
Couple of minor points, but this is urgently needed so I'm going to go ahead and merge it.

---

Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/108#-:-L7ZsdDWL-nNJUG8ZlJm:b-y1vmf3)*

**Pull request merged**
