### PR TITLE
Bl 5537 Force CQ pages to portrait orientation.

### PR DESCRIPTION
**Pull request by rjconrad**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/94)

### CODE REVIEW

**Comment by JohnThomson** [comment]
If I'm reading the constants correctly, we're only controlling the orientation if the user has turned off sensor orientation. So if the sensor orientation is on, and the user has put the device in landscape mode to better read a landscape book, it will stay that way even for CQs. Is that right? Is it what we want? Quite possibly, but maybe worth checking with @hatton.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 131 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/94#-L4HMQTdVQBFYhVyJ8rO:-L4HMQTeEvz7-pMyLVVd:b-gx0jxb) ([raw file](https://github.com/bloombooks/bloomreader/blob/3f8322ce5a4664409d2120501ac7d7c6f9b0e386/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L131)):*
> ```Java
>     @Override
>     public void onConfigurationChanged(Configuration newConfig){
>         // This prevents the activity from restarting when we change the orientation
> ```

That's really bizarre. We override a method, call the base method without changing the arguments or doing anything additional, and it produces a different result? If true, a little more explanation might be helpful.
Do we not want it to restart? Can we switch the layout appropriately without a restart?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/94#-:-L4HNvODps02LkM3IF-0:b-j0072v)*

**Comment by hatton** [comment]
Let's go with how it is and ask the PNG folks what they like. They are living with BR all day every day now, and so I trust their views a lot more than my own.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/94#-:-L4HjOaaO7tgB-OUUx3h:b-qvego4)*

**Comment by rjconrad** [comment]
@JohnThompson No, that's not what those constants mean.  SCREEN_ORIENTATION_SENSOR_LANDSCAPE forces the display to be landscape, but the user can switch between the two possible landscape orientations by turning his phone. Likewise for Portrait, although most phones do not allow an upside-down portrait orientation in my experience.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/org/sil/bloom/reader/ReaderActivity.java, line 131 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/94#-L4HMQTdVQBFYhVyJ8rO:-L4KKrthujp_tyOjXEu0:b26ueut) ([raw file](https://github.com/bloombooks/bloomreader/blob/3f8322ce5a4664409d2120501ac7d7c6f9b0e386/app/src/main/java/org/sil/bloom/reader/ReaderActivity.java#L131)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That's really bizarre. We override a method, call the base method without changing the arguments or doing anything additional, and it produces a different result? If true, a little more explanation might be helpful.
Do we not want it to restart? Can we switch the layout appropriately without a restart?
</blockquote></details>

I was going to say that, without implementing this, Android starts the whole activity over with onCreate. Besides gross inefficiency, this was causing the activity to reset the screen orientation to the book's orientation (landscape). Then it was jumping back to the CQ page which set the orientation back to portrait and started the process all over again. It would thrash like that for a few seconds and finally drop me off on page 1.

On second look, however, implementing the override isn't what counts - all we needed was the line in the manifest telling it that this activity should handle config changes. So I've dropped it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/94#-:-L4KIJDL1aZl6o9XFM7A:b-tjsobb)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/94#-:-L4Lxa-hRARMDdT5diYx:bnfp4nl)*

**Pull request merged**
