### PR TITLE
Add form for entering device info for analytics (BL-10880)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/281)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Making draft for now. I realized I didn't test (and it probably doesn't work) that the live analytics are changed on the fly.

**Comment by andrew-polk** [comment]
Ready for review now.

**Review by JohnThomson — APPROVED** [review]
A few questions and minor suggestions.
I suppose we don't need any more security on this? I could imagine one kid in a class accidentally discovering it and spreading the word, and all of them changing their device IDs to something silly or naughty. Not that it's obvious what we could do without being a great nuisance to the people who are supposed to set them up...

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/281#-:-MurY0kv4JXEN07EhFU2:b-hutuyd)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/281#-MurUSej-6n9yAAXrxzy:-MurUSej-6n9yAAXrxzz:bjbqws3) ([raw file](https://github.com/bloombooks/bloomreader/blob/df859c3124483be4e2e89461e28abf40b806d956/app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java#L13)):*
> ```Java
> import android.widget.EditText;
> 
> public class DeviceInfoDialogFragment extends DialogFragment {
> ```

DeviceInfo could mean a lot of things. DeviceIdDialogFragment? I think it deserves a class comment briefly describing what it is designed to do and the deliberately obscure way it gets launched.
___
*[app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/281#-MurV-yQCqPS3D9gRMYI:-MurV-yQCqPS3D9gRMYJ:bcy3rcm) ([raw file](https://github.com/bloombooks/bloomreader/blob/df859c3124483be4e2e89461e28abf40b806d956/app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java#L42)):*
> ```Java
>             boolean isValid = true;
>             if (isEmpty(deviceId)) {
>                 deviceId.setError("device ID is required");
> ```

Surprises me somewhat. This can't be used to remove a device Id? What if you entered one by mistake on a device which wasn't supposed to be part of this project?
___
*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 1099 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/281#-MurX0Il6mWE48LDzvWX:-MurX0Il6mWE48LDzvWY:bvnf1kr) ([raw file](https://github.com/bloombooks/bloomreader/blob/df859c3124483be4e2e89461e28abf40b806d956/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L1099)):*
> ```Java
>         } else if (id == R.id.analytics_device_id_info || id == R.id.analytics_status) {
>             if (!processDeviceIdInfoClick()) {
>                 // If we haven't handled the click, don't close the drawer
> ```

It's a bit non-obvious that the drawer is not closed because we returned early, not because we returned true. " If we haven't handled the click, return without closing the drawer so the user has the opportunity to tap again, which eventually activates the secret behavior"?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/281)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[app/src/main/java/org/sil/bloom/reader/MainActivity.java, line 1099 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/281#-MurX0Il6mWE48LDzvWX:-MuwLJUKEuP7NqCDGfcB:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/df859c3124483be4e2e89461e28abf40b806d956/app/src/main/java/org/sil/bloom/reader/MainActivity.java#L1099)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's a bit non-obvious that the drawer is not closed because we returned early, not because we returned true. " If we haven't handled the click, return without closing the drawer so the user has the opportunity to tap again, which eventually activates the secret behavior"?
</blockquote></details>

Done.
___
*[app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/281#-MurUSej-6n9yAAXrxzy:-MuwRjHaD83cEnHhsrja:b-896fix) ([raw file](https://github.com/bloombooks/bloomreader/blob/df859c3124483be4e2e89461e28abf40b806d956/app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

DeviceInfo could mean a lot of things. DeviceIdDialogFragment? I think it deserves a class comment briefly describing what it is designed to do and the deliberately obscure way it gets launched.
</blockquote></details>

Done.
___
*[app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomreader/281#-MurV-yQCqPS3D9gRMYI:-MuwRli1EBqJx-UznZXV:b-474272) ([raw file](https://github.com/bloombooks/bloomreader/blob/df859c3124483be4e2e89461e28abf40b806d956/app/src/main/java/org/sil/bloom/reader/DeviceInfoDialogFragment.java#L42)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Surprises me somewhat. This can't be used to remove a device Id? What if you entered one by mistake on a device which wasn't supposed to be part of this project?
</blockquote></details>

See comments.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
