### PR TITLE
Rework UI for Share App dialog (BL-5093)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomreader/47)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/values/strings.xml, line 35 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/47#-Kw0wNutd_SuzM2hBm9C:-Kw0wNutd_SuzM2hBm9D:bwpesmc) ([raw file](https://github.com/bloombooks/bloomreader/blob/b444eb1a73e4415d2cfad0ca7930ce046fd03b57/app/src/main/res/values/strings.xml#L35)):*
> ```XML
>     <string name="share_app_link"><u>Share the link to get Bloom Reader on Google Play</u></string>
>     <string name="share_app_with_friend">Share this Bloom Reader app with a friend!</string>
>     <string name="share_app_via">Share App via</string>
> ```

When I first did the link thing, I say "Share App via" and thought "maybe I clicked the wrong thing?". Could we instead have that case say "Share Link via"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/47)*

**Comment by hatton** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/values/strings.xml, line 35 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/47#-Kw0wNutd_SuzM2hBm9C:-Kw0w_z0DuYJIejUM3IS:bkgljfd) ([raw file](https://github.com/bloombooks/bloomreader/blob/b444eb1a73e4415d2cfad0ca7930ce046fd03b57/app/src/main/res/values/strings.xml#L35)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

When I first did the link thing, I say "Share App via" and thought "maybe I clicked the wrong thing?". Could we instead have that case say "Share Link via"?
</blockquote></details>

I *saw*, not *say*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/47)*

**Comment by hatton** [comment]
lgtm

Added a small request that isn't really related to this change.

**Comment by andrew-polk** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/values/strings.xml, line 35 at r1](https://reviewable.io:443/reviews/bloombooks/bloomreader/47#-Kw0wNutd_SuzM2hBm9C:-Kw0yiYNjNNAtdAK0ms6:by6evwg) ([raw file](https://github.com/bloombooks/bloomreader/blob/b444eb1a73e4415d2cfad0ca7930ce046fd03b57/app/src/main/res/values/strings.xml#L35)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I *saw*, not *say*
</blockquote></details>

I wondered about that myself. Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomreader/47)*

**Pull request merged**
